export const mockDashboardStats = {
  totalJobs: 45,
  activeJobs: 23,
  totalCandidates: 1247,
  interviewsScheduled: 18,
  onboardingInProgress: 7,
  totalEmployees: 156,
  presentToday: 142,
  attendanceRate: 91.0,
}

export const mockRecentActivity = [
  {
    id: 1,
    type: "interview",
    message: "Interview scheduled with Sarah Johnson for Senior Developer position",
    time: "2 hours ago",
    status: "scheduled",
  },
  {
    id: 2,
    type: "application",
    message: "New application received for Marketing Manager role",
    time: "4 hours ago",
    status: "new",
  },
  {
    id: 3,
    type: "onboarding",
    message: "John Smith completed onboarding documentation",
    time: "6 hours ago",
    status: "completed",
  },
  {
    id: 4,
    type: "interview",
    message: "Interview completed for UI/UX Designer position",
    time: "1 day ago",
    status: "completed",
  },
]

export const mockPipelineData = [
  { stage: "Applied", count: 245, color: "#3b82f6" },
  { stage: "Screening", count: 89, color: "#8b5cf6" },
  { stage: "Interview", count: 34, color: "#06b6d4" },
  { stage: "Offer", count: 12, color: "#10b981" },
  { stage: "Hired", count: 8, color: "#f59e0b" },
]

export const mockNotifications = [
  {
    id: 1,
    title: "Interview Reminder",
    message: "Interview with Sarah Johnson in 30 minutes",
    time: "30 min",
    type: "reminder",
    unread: true,
  },
  {
    id: 2,
    title: "New Application",
    message: "New application for Senior Developer position",
    time: "2 hours",
    type: "application",
    unread: true,
  },
  {
    id: 3,
    title: "Onboarding Complete",
    message: "John Smith completed all onboarding tasks",
    time: "4 hours",
    type: "success",
    unread: false,
  },
]

export const mockOnboardingEmployees = [
  {
    id: 1,
    name: "Alex Chen",
    position: "Frontend Developer",
    department: "Engineering",
    startDate: "2024-01-15",
    progress: 75,
    status: "in-progress",
    avatar: "/placeholder-user.jpg",
  },
  {
    id: 2,
    name: "Maria Garcia",
    position: "Product Manager",
    department: "Product",
    startDate: "2024-01-20",
    progress: 45,
    status: "in-progress",
    avatar: "/placeholder-user.jpg",
  },
  {
    id: 3,
    name: "David Kim",
    position: "Data Analyst",
    department: "Analytics",
    startDate: "2024-01-22",
    progress: 90,
    status: "in-progress",
    avatar: "/placeholder-user.jpg",
  },
]

// Payroll and Attendance Mock Data
export const mockEmployees = [
  {
    id: "EMP001",
    name: "Rajesh Kumar",
    designation: "Senior Software Engineer",
    department: "Engineering",
    basicSalary: 85000,
    allowances: {
      hra: 25500,
      transport: 2400,
      medical: 1500,
      special: 5000,
    },
    deductions: {
      pf: 10200,
      esi: 850,
      tax: 12000,
      other: 500,
    },
    attendance: {
      present: 22,
      absent: 1,
      late: 2,
      overtime: 8,
      percentage: 95.7,
    },
    lastCheckIn: "09:15 AM",
    status: "Present",
    avatar: "/placeholder-user.jpg",
  },
  {
    id: "EMP002",
    name: "Priya Sharma",
    designation: "Product Manager",
    department: "Product",
    basicSalary: 95000,
    allowances: {
      hra: 28500,
      transport: 2400,
      medical: 1500,
      special: 7000,
    },
    deductions: {
      pf: 11400,
      esi: 950,
      tax: 15000,
      other: 300,
    },
    attendance: {
      present: 23,
      absent: 0,
      late: 1,
      overtime: 5,
      percentage: 100,
    },
    lastCheckIn: "08:45 AM",
    status: "Present",
    avatar: "/placeholder-user.jpg",
  },
  {
    id: "EMP003",
    name: "Amit Patel",
    designation: "UI/UX Designer",
    department: "Design",
    basicSalary: 65000,
    allowances: {
      hra: 19500,
      transport: 2400,
      medical: 1500,
      special: 3000,
    },
    deductions: {
      pf: 7800,
      esi: 650,
      tax: 8000,
      other: 200,
    },
    attendance: {
      present: 21,
      absent: 2,
      late: 3,
      overtime: 3,
      percentage: 91.3,
    },
    lastCheckIn: "09:30 AM",
    status: "Present",
    avatar: "/placeholder-user.jpg",
  },
  {
    id: "EMP004",
    name: "Sneha Reddy",
    designation: "HR Manager",
    department: "Human Resources",
    basicSalary: 75000,
    allowances: {
      hra: 22500,
      transport: 2400,
      medical: 1500,
      special: 4000,
    },
    deductions: {
      pf: 9000,
      esi: 750,
      tax: 10000,
      other: 400,
    },
    attendance: {
      present: 23,
      absent: 0,
      late: 0,
      overtime: 2,
      percentage: 100,
    },
    lastCheckIn: "08:30 AM",
    status: "Present",
    avatar: "/placeholder-user.jpg",
  },
]

export const mockAttendanceRecords = [
  {
    id: 1,
    employeeId: "EMP001",
    employeeName: "Rajesh Kumar",
    date: "2024-01-28",
    checkIn: "09:15:23",
    checkOut: "18:45:12",
    workingHours: "09:29:49",
    overtime: "01:29:49",
    status: "Present",
    device: "Biometric Scanner 1",
    location: "Main Entrance",
  },
  {
    id: 2,
    employeeId: "EMP002",
    employeeName: "Priya Sharma",
    date: "2024-01-28",
    checkIn: "08:45:15",
    checkOut: "17:30:45",
    workingHours: "08:45:30",
    overtime: "00:45:30",
    status: "Present",
    device: "Biometric Scanner 2",
    location: "Office Floor 2",
  },
  {
    id: 3,
    employeeId: "EMP003",
    employeeName: "Amit Patel",
    date: "2024-01-28",
    checkIn: "09:30:45",
    checkOut: "18:15:30",
    workingHours: "08:44:45",
    overtime: "00:44:45",
    status: "Present",
    device: "Biometric Scanner 1",
    location: "Main Entrance",
  },
  {
    id: 4,
    employeeId: "EMP004",
    employeeName: "Sneha Reddy",
    date: "2024-01-28",
    checkIn: "08:30:00",
    checkOut: "17:00:00",
    workingHours: "08:30:00",
    overtime: "00:30:00",
    status: "Present",
    device: "Biometric Scanner 3",
    location: "HR Department",
  },
]

export const mockBiometricDevices = [
  {
    id: "BIO001",
    name: "Main Entrance Scanner",
    location: "Ground Floor - Main Entrance",
    status: "Online",
    lastSync: "2024-01-28 14:30:00",
    todayScans: 156,
    successRate: 98.5,
    model: "ZKTeco F18",
  },
  {
    id: "BIO002",
    name: "Office Floor 2 Scanner",
    location: "Second Floor - Office Area",
    status: "Online",
    lastSync: "2024-01-28 14:29:45",
    todayScans: 89,
    successRate: 97.8,
    model: "ZKTeco F18",
  },
  {
    id: "BIO003",
    name: "HR Department Scanner",
    location: "Third Floor - HR Department",
    status: "Online",
    lastSync: "2024-01-28 14:31:12",
    todayScans: 34,
    successRate: 99.1,
    model: "ZKTeco F18",
  },
  {
    id: "BIO004",
    name: "Cafeteria Scanner",
    location: "Ground Floor - Cafeteria",
    status: "Offline",
    lastSync: "2024-01-28 12:15:30",
    todayScans: 0,
    successRate: 0,
    model: "ZKTeco F18",
  },
]

export const mockLiveActivity = [
  {
    id: 1,
    employeeName: "Rajesh Kumar",
    employeeId: "EMP001",
    action: "Check In",
    time: "09:15:23",
    device: "Main Entrance Scanner",
    status: "Success",
  },
  {
    id: 2,
    employeeName: "Priya Sharma",
    employeeId: "EMP002",
    action: "Check In",
    time: "08:45:15",
    device: "Office Floor 2 Scanner",
    status: "Success",
  },
  {
    id: 3,
    employeeName: "Amit Patel",
    employeeId: "EMP003",
    action: "Check In",
    time: "09:30:45",
    device: "Main Entrance Scanner",
    status: "Success",
  },
  {
    id: 4,
    employeeName: "Unknown User",
    employeeId: "N/A",
    action: "Failed Scan",
    time: "10:15:30",
    device: "Cafeteria Scanner",
    status: "Failed",
  },
]
